### ISSUE TITLE
English language not working, always french

### ISSUE THREAD

**Issue by Jikstra** [phug-php/website#3]
Even if I select english as my language i only get french texts on the website (except of menu titles).

Screenshot:
https://i.imgur.com/iEcVfEc.png

**Comment by kylekatarnls** [comment]
Thanks regression confirmed. I inspect.

Meanwhile you can read the source here: https://github.com/phug-php/website/tree/master/doc/en

**Comment by kylekatarnls** [comment]
Hi, thanks for your help, all languages used the same cache directory after I recently enable cache on production. Fixed.

English documentation: https://en.phug-lang.com/
French documentation: https://fr.phug-lang.com/
