### ISSUE TITLE
Huge CPU and network load during quick scroll

### ISSUE THREAD

**Issue by acelot** [phug-php/website#5]
When I quick scroll down the page the iframes with examples simultaneously starts loading causing huge CPU load and network connections. It hangs the browser and sometimes breaks the Chrome tab.

It would be cool if the iframes were loaded with some delay after scrolling is ended. Also you can use [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) to detect which part of iframe is visible to user (in percents).

[![screenshot-www youtube com 2018 04 03 09-06-04](https://user-images.githubusercontent.com/1065215/38225252-413a2868-371e-11e8-9098-0adb2e9601f3.png)](https://youtu.be/9Wau6bZs0ZI)

**Comment by kylekatarnls** [comment]
Hi, my machine has enough resources to quick scroll with no trouble, so I would be OK with a fallback solution (something like on 3 iframes loading, delay other loadings) but I would keep it fast to load and display for powerful machines. I would avoid to slow down all iframe load to fix it.
