### ISSUE TITLE
Website seems broken

### ISSUE THREAD

**Issue by mhf-ir** [phug-php/website#8]

**Comment by kylekatarnls** [comment]
Thank you for the notification and sorry for inconvenience.
https://phug-lang.com/

**Comment by paulbrzeski** [comment]
Hey @kylekatarnls 

The website is down again.

Just FYI in case you aren't aware

**Comment by kylekatarnls** [comment]
Yes, troubles with hosting, I hope this can be fixed soon.

**Comment by paulbrzeski** [comment]
IIRC the site was fairly straightforward, perhaps you could replace it with a free [Github Pages](https://pages.github.com/) site?

I use a Pug based script I wrote to generate static HTML sites, as you're familiar with Pug you may like it - https://github.com/paulbrzeski/kettlefish

**Comment by kylekatarnls** [comment]
You can read the markdown source on GitHub:
https://github.com/phug-php/website/tree/master/doc/en

Thanks.

**Comment by kylekatarnls** [comment]
Closing this as https://phug-lang.com/ is up now (for weeks actually but I forgot this issue was open).
